CREATE TABLE DOGSMANAGER.DOGS (
  ID INT NOT NULL AUTO_INCREMENT,
  DOG_NAME VARCHAR(100) NOT NULL,
  DOG_BIRTH DATE NOT NULL,
  DOG_HEIGHT FLOAT NOT NULL,
  DOG_WEIGHT FLOAT NOT NULL,
  PRIMARY KEY (ID));